### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by denghp** [deerawan/yii2-advanced-api#5]
#nginx api 
```
server {
    charset utf-8;
    client_max_body_size 128M;
    set $fcgi_server 127.0.0.1:9000;
        
    listen 80; ## listen for ipv4

    server_name api.denghp.com;
    root        /home/denghp/webroot/yii2-advanced-api/web;
    index       index.php;

    access_log  /usr/local/nginx/logs/yii2_demo_api_access.log main;
    error_log   /usr/local/nginx/logs/yii2_demo_api_error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }                                                                                                                                          

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass $fcgi_server;
    }   

    location ~ /\.(ht|svn|git) {
        deny all;
    }   
}
```
-------------
```
http://api.denghp.com/v1/countries not working
http://api.denghp.com/v1/country not working

Not Found (#404)

Page not found.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.
```

error message
```
2015-06-09 21:42:12 [127.0.0.1][-][-][error][yii\web\HttpException:404] exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /home/denghp/webroot/yii2-advanced-api/vendor/yiisoft/yii2/web/Request.php:187
Stack trace:
#0 /home/denghp/webroot/yii2-advanced-api/vendor/yiisoft/yii2/web/Application.php(75): yii\web\Request->resolve()
#1 /home/denghp/webroot/yii2-advanced-api/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /home/denghp/webroot/yii2-advanced-api/api/web/index.php(17): yii\base\Application->run()
#3 {main}
2015-06-09 21:42:12 [127.0.0.1][-][-][info][application] $_SERVER = [
    'USER' => 'denghp'
    'HOME' => '/home/denghp'
    'FCGI_ROLE' => 'RESPONDER'
    'QUERY_STRING' => ''
    'REQUEST_METHOD' => 'GET'
    'CONTENT_TYPE' => 'text/plain; charset=utf-8'
    'CONTENT_LENGTH' => ''
    'SCRIPT_NAME' => '/index.php'
    'REQUEST_URI' => '/v1/countris'
    'DOCUMENT_URI' => '/index.php'
    'DOCUMENT_ROOT' => '/home/denghp/webroot/yii2-advanced-api/api/web'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_SOFTWARE' => 'nginx/1.7.8'
    'REMOTE_ADDR' => '127.0.0.1'
    'REMOTE_PORT' => '60919'
    'SERVER_ADDR' => '127.0.0.1'
    'SERVER_PORT' => '80'
    'SERVER_NAME' => 'api.denghp.com'
    'REDIRECT_STATUS' => '200'
    'SCRIPT_FILENAME' => '/home/denghp/webroot/yii2-advanced-api/api/web/index.php'
    'HTTP_HOST' => 'api.denghp.com'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36'
    'HTTP_CONTENT_TYPE' => 'text/plain; charset=utf-8'
    'HTTP_ACCEPT' => '*/*'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch'
    'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-GB;q=0.6,en;q=0.4,en-US;q=0.2'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1433857332.8264
    'REQUEST_TIME' => 1433857332
]
```

**Comment by stingbo** [comment]
I have the same problme with @denghp,please help me ,thanks! @deerawan

**Comment by mastershaig** [comment]
Same problem with @denghp , please Help !
